cache:
  directories: src/main/resources/webassets/node_modules/

matrix:
  include:
    - name: "Back-end style"
      language: java
      install: mvn compile -DskipTests=true -B -V -Dfmt.skip=true
      script: mvn fmt:check

    - name: "Back-end unit tests"
      language: java
      install: mvn compile -DskipTests=true -B -V -Dfmt.skip=true
      script: mvn test -B -Dfmt.skip=true

    - name: "Front-end style"
      language: node_js
      node_js: "node"
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
        - export PATH=$HOME/.yarn/bin:$PATH
      install:
        - cd src/main/resources/webassets
        - yarn install
      script: yarn check-format

    - name: "Front-end unit tets"
      language: node_js
      node_js: "node"
      addons:
        chrome: stable
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
        - export PATH=$HOME/.yarn/bin:$PATH
      install:
        - cd src/main/resources/webassets
        - yarn install
      script: yarn test
